name: Trigger deploy in MSPR-TPRE-601

on:
  push:
    branches:
      - dev

jobs:
  notify-deployment-repo:
    runs-on: ubuntu-latest
    environment: "MSPR 601"
    steps:
    - name: Trigger deployment CI
      run: |
        curl -X POST https://api.github.com/repos/Enzobu/MSPR-TPRE-601/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.DEPLOY_TRIGGER_TOKEN }}" \
          -d '{"event_type": "trigger-deploy"}'